### ISSUE TITLE
ChromeOS and Android App unable to connect to GHS Server

### ISSUE THREAD

**Issue by jshank** [Lurkars/gloomhavensecretariat#295]
I'm unable to connect to my GHS server using the installed Web app (ChromeOS). It works fine from the web browser on the same device though. When I select secure (not a secure server) and try to connect again, I can see an error in the docker logs on the actual server so I know it's configured for the right IP and port. Is there a client count limitation or other way to debug why it won't connect? Interestingly, the Web app does work on my Win10 machine. I'm unable to get web/native apps to connect from ChromeOS or my Pixel 7 Pro.

docker-compose.yaml
```
version: "3.8"
services:
  ghs-server:
    container_name: ghs-server
    image: gloomhavensecretariat/ghs-server
    volumes:
      - ./config:/root/.ghs
    ports:
      - "8094:8094"
```

application.properties
```
ghs-server.lastestClientOnStartup=true
server.port=8094
ghs-server.public=true
ghs-server.externalHost=10.1.10.2
```
